### ISSUE TITLE
Implementation of Performer

### ISSUE THREAD

**Issue by lucastononrodrigues** [cloneofsimo/smallest_working_performer#2]
Isn't your implementation of performer with quadratic complexity?

Because of the prm_exp function you will compute x^2 directly without using the problem formulation of the article, which consists in applying the phi(Q) phi(K) phi(V) in order to linearize the problem with equivalent result of the SM(x,y).

That can be useful to check how performers work in small datasets though.

**Comment by cloneofsimo** [comment]
I don't exactly understand, because in prm_exp time complexity should be O(N * L * m* d) where L is number of tokens, m is number of random features, d is hidden_dim. Notice that by Linear complexity they intend operation of "L^2", as in some cases m , d << L .
By the way, phi(V) is not needed.
Anyways I could be wrong on the complexity of this specific implementation, so do remind me again if I am wrong. But thank you very much checking out my code!

**Comment by lucastononrodrigues** [comment]
You are right, sorry, I messed up on the dimensions interpretation.
